#!/usr/bin/env bash
assignment=${1?Error: no name given}
cd ~/fum-os161/os161-1.99;
printf "===================== os161 configure result =====================\n" > ~/fum-os161/install_output.txt;
./configure --ostree=$HOME/fum-os161/root --toolprefix=fum- >> ~/fum-os161/install_output.txt;
printf "\n\n" >> ~/fum-os161/install_output.txt;
cd kern/conf;
printf "===================== Assignment config result =====================\n" >> ~/fum-os161/install_output.txt;
./config $assignment >> ~/fum-os161/install_output.txt;
printf "\n\n" >> ~/fum-os161/install_output.txt;
cd ../compile/$assignment;
printf "===================== bmake depend result =====================\n" >> ~/fum-os161/install_output.txt;
bmake depend >> ~/fum-os161/install_output.txt;
printf "\n\n" >> ~/fum-os161/install_output.txt;
printf "===================== bmake result =====================\n" >> ~/fum-os161/install_output.txt;
bmake >> ~/fum-os161/install_output.txt;
printf "\n\n" >> ~/fum-os161/install_output.txt;
printf "===================== bmake install result =====================\n" >> ~/fum-os161/install_output.txt;
bmake install >> ~/fum-os161/install_output.txt;
printf "\n\n" >> ~/fum-os161/install_output.txt;

